# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11sm0uRbTfQBmI8O1CVn__Hq4Y0rR_YdV
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
from sklearn.model_selection import train_test_split, GridSearchCV,cross_val_score
from sklearn.neighbors import KNeighborsRegressor
from sklearn.neighbors import KNeighborsClassifier

df = pd.read_csv("Social_Network_Ads.csv")

df = df.drop(['Gender'], axis=1)

df

X = df.drop(['Purchased','Age'], axis='columns')
y =df.Purchased

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

len(X_train)
len(X_test)

len(X_test)

from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5)

df

knn.fit(X_train, y_train)

knn.score(X_test, y_test)

